In [368]:
import numpy as np
A = np.array ([2,5,10]) 
A.dtype

dtype('int64')

In [369]:
B=np.array ([2.4,10.6,5.2]) 
B.dtype

dtype('float64')

In [370]:
A=np.array([(3,4,5),(12,6,1)])
print(A)

[[ 3  4  5]
 [12  6  1]]


In [371]:
Z=np.zeros((2,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [372]:
A = np.ones((3,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [373]:
S=np.arange(10,30,5)
print (S)

[10 15 20 25]


In [374]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [375]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [376]:
import random
random.choice([1,2,3,4,5])

1

In [377]:
random.choice('python')

'h'

In [378]:
random.randrange(25,50)

40

In [379]:
random.randrange(25,50,2)

43

In [380]:
random.uniform(5,10)

5.074162230122768

In [381]:
random.random()

0.46258050809294915

In [382]:
import random
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

[2, 1, 5, 3, 4]


In [383]:
import random
random.seed(10)
random_number = random.randint(1, 100)
print("Random number generated with seed 10:", random_number)

Random number generated with seed 10: 74


In [384]:
a = np.arange(15).reshape(3, 5)
a.size

15