In [2427]:
import numpy as np
A = np.array ([2,5,10]) 
A.dtype

dtype('int64')

In [2428]:
B=np.array ([2.4,10.6,5.2]) 
B.dtype

dtype('float64')

In [2429]:
A=np.array([(3,4,5),(12,6,1)])
print(A)

[[ 3  4  5]
 [12  6  1]]


In [2430]:
Z=np.zeros((2,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2431]:
A = np.ones((3,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2432]:
S=np.arange(10,30,5)
print (S)

[10 15 20 25]


In [2433]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [2434]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [2435]:
import random
random.choice([1,2,3,4,5])

1

In [2436]:
random.choice('python')

'h'

In [2437]:
random.randrange(25,50)

40

In [2438]:
random.randrange(25,50,2)

43

In [2439]:
random.uniform(5,10)

5.074162230122768

In [2440]:
random.random()

0.46258050809294915

In [2441]:
import random
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

[2, 1, 5, 3, 4]


In [2442]:
import random
random.seed(10)
random_number = random.randint(1, 100)
print("Random number generated with seed 10:", random_number)

Random number generated with seed 10: 74


In [2443]:
a = np.arange(15).reshape(3, 5)
a.size

15

In [2444]:
a = np.arange(15).reshape(3, 5)
a.shape

(3, 5)

In [2445]:
a = np.arange(15).reshape(3, 5)
b = a.T
b.shape

(5, 3)

In [2446]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [2447]:
c.shape

(2, 3, 4)

In [2448]:
c[1,...]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [2449]:
c[1,:,:]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [2450]:
c[...,2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [2451]:
c[:,:,2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [2452]:
a = np.array( [20,30,40,50] ) 
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [2453]:
c = a-b
c

array([20, 29, 38, 47])

In [2454]:
b**2

array([0, 1, 4, 9])

In [2455]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [2456]:
a<35

array([ True,  True, False, False])

In [2457]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B     # elementwise product

array([[2, 0],
       [0, 4]])

In [2458]:
A.dot(B)        # matrix product

array([[5, 4],
       [3, 4]])

In [2459]:
np.dot(A, B) # another matrix product

array([[5, 4],
       [3, 4]])

In [2460]:
b = np.arange(12).reshape(3,4) 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2461]:
b.sum(axis=0)       # sum of each column

array([12, 15, 18, 21])

In [2462]:
b.sum(axis=1)       #sum of each row

array([ 6, 22, 38])

In [2463]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [2464]:
a[2:5]

array([ 8, 27, 64])

In [2465]:
a[0:6:2]

array([ 0,  8, 64])

In [2466]:
b = np.array([[ 0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33],
[40, 41, 42, 43]])
b[2,3]

23

In [2467]:
b[0:5,1]        #or b[:5,1] or b[:,1]

array([ 1, 11, 21, 31, 41])

In [2468]:
b[-1,:] # will fetch last row 

array([40, 41, 42, 43])

In [2469]:
b[:,-1] # will fetch last col

array([ 3, 13, 23, 33, 43])

In [2470]:
for row in b:
    print(row) # will print every row

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [2471]:
for element in b.flat:
    print (element) # will show all elements of b in 1−D array

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [2472]:
b.ravel() # returns the array flattened to (1x 20)

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [2473]:
B1=b.reshape(4,5)
print(B1)

[[ 0  1  2  3 10]
 [11 12 13 20 21]
 [22 23 30 31 32]
 [33 40 41 42 43]]


In [2474]:
A1=np.array([(3,4,5),(12,6,1)])
A2=np.array([(1,2,6),(-4,3,8)])
D1=np.vstack((A1,A2))
D2=np.hstack((A1,A2))
print(D1)

[[ 3  4  5]
 [12  6  1]
 [ 1  2  6]
 [-4  3  8]]


In [2475]:
print(D2)

[[ 3  4  5  1  2  6]
 [12  6  1 -4  3  8]]


In [2476]:
a = np.array([4.,2.]) 
b = np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [2477]:
np.hstack((a,b)) 
# the result is different

array([4., 2., 3., 8.])

In [2478]:
a = np.arange(12)**2
i = np.array( [ 1,1,3,8,5 ] )
a[i]

array([ 1,  1,  9, 64, 25])

In [2479]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
a[j]

array([[ 9, 16],
       [81, 49]])

In [2480]:
import numpy as np 
a=np.array([(3,2,9),(1,6,7)])
s1=0
for row in a:
    for col in row: 
        s1+=col
print(s1)

28


In [2481]:
import numpy as np 
a=np.array([(3,2,9),(1,6,7)]) 
s=0
for i in range(a.shape[0]):
    for j in range(a.shape[1]): 
        s+=a[i,j]
print(s)

28
